### PR TITLE
fix: constrain components to block range from block numbers store

### LINKED ISSUE #257: Fix: Constrain components to block range from block numbers store
## Context

Components currently calculate dates like "yesterday" dynamically and attempt to scan blocks that may not exist in the block numbers store. This causes unnecessary RPC calls and potential errors when the store's data is not up-to-date, making the system less reliable when operating on historical data or in environments where real-time data isn't available.

## Current Behavior

1. Components like `recipient-recieved-scanner` and `orchestrator` calculate "yesterday" as `new Date() - 1 day`
2. The scanner attempts to scan up to "yesterday" regardless of what's in the block numbers store
3. If the block numbers store only has data up to 2024-05-02, but today is 2024-05-04, the scanner tries to find blocks for 2024-05-03
4. This results in RPC calls for blocks that don't exist in the store's date range
5. Components may fail or produce incorrect results when querying beyond stored data
6. The system assumes real-time operation instead of being bounded by available data

## Expected Behavior

- Components should query the block numbers store to determine the minimum and maximum available dates
- Scanning should be constrained to the date range available in the block numbers store
- No component should calculate "yesterday" or any other dynamic date
- If an end date is not provided via CLI, use the maximum date from the block numbers store
- If a start date is not provided via CLI, use the minimum date from the block numbers store
- Components should work reliably with historical data without assuming real-time operation
- Each component should access the store independently to get the max and min block numbers
- No component, except maybe the file manager, should change their public interface. 

## Required Context

- `src/recipient-recieved-scanner.ts` - lines 116-120 show the "yesterday" calculation
- `src/orchestrator.ts` - lines 32-35 show default end date as "yesterday"
- `src/balance-fetcher.ts` - lines 139-141 show filtering by block numbers (good pattern to follow)
- `src/types/index.ts` - BlockNumbersData interface for understanding the store structure
- `__tests__/units/recipient-recieved-scanner/scan-distributor-events.test.ts` - test showing issues with date boundaries

## Blocking Issues

None

## Out of Scope

- Changing the block numbers file format or structure
- Modifying how block numbers are initially populated
- Changing the public interface of any component except the filemanager
- Changing the CLI parameter handling (just changing defaults)
- Adding new date validation beyond using store boundaries

### PR DESCRIPTION
**Pull request by yahgw-ai**
## Summary
This PR fixes issue #257 by constraining components to use the actual date range available in the block numbers store instead of calculating dynamic dates.

### RecipientReceivedScanner
- Removed dynamic "yesterday" calculation in scan method
- Query block numbers store to get max available date
- Use max date from store as end date for scanning
- Skip dates that don't exist in block store instead of throwing errors
- Extract helper methods for better code organization

### Orchestrator
- Remove SAFE_BLOCK_OFFSET usage and dynamic date calculation
- Get min/max dates from block numbers store when dates not provided via CLI
- Throw clear error when block store is empty or missing and no dates provided
- Extract helper functions to reduce code duplication

## Testing
- Added comprehensive unit tests for both components following TDD approach
- All unit tests pass (529 passing)
- One integration test fails as it was testing the old "yesterday" behavior, which is expected

## Notes
- Each component now independently accesses the block numbers store to determine date ranges
- No changes to public interfaces (except internal FileManager usage)
- Components now work reliably with historical data without assuming real-time operation

Fixes #257

### CODE REVIEW

File: src/infrastructure/orchestration/orchestrator.ts [hunk 1]
```diff
@@ -82,6 +46,48 @@ async function parseDateRange(
...
+
+  const sortedDates = Object.keys(blockNumbersData.blocks).sort();
+  if (sortedDates.length === 0) {
+    throw new Error("No block numbers found in store and no dates provided");
+  }
+
+  return { sortedDates };
+}
+
+function getMaxDateFromBlockStore(fileManager: FileManager): Date {
```
Comment (yahgwai) [inline src/infrastructure/orchestration/orchestrator.ts]: This should be on the file manager

File: src/infrastructure/orchestration/orchestrator.ts [hunk 2]
```diff
@@ -82,6 +46,48 @@ async function parseDateRange(
...
+  const { sortedDates } = getDateRangeFromBlockStore(fileManager);
+  const maxDateStr = sortedDates[sortedDates.length - 1];
+  if (!maxDateStr) {
+    throw new Error("No block numbers found in store and no dates provided");
+  }
+  return new Date(maxDateStr);
+}
+
+function getMinDateFromBlockStore(fileManager: FileManager): Date {
```
Comment (yahgwai) [inline src/infrastructure/orchestration/orchestrator.ts]: This should be on the file manager

File: src/infrastructure/orchestration/orchestrator.ts [hunk 3]
```diff
@@ -82,6 +46,48 @@ async function parseDateRange(
...
 
+function parseConfigDate(dateStr: string, dateType: string): Date {
+  const date = new Date(dateStr);
+  if (isNaN(date.getTime())) {
+    throw new Error(`Invalid ${dateType} date format`);
+  }
+  return date;
+}
+
+function getDateRangeFromBlockStore(fileManager: FileManager): {
```
Comment (yahgwai) [inline src/infrastructure/orchestration/orchestrator.ts]: Perhaps this should also be on the file manager

**Comment by yahgw-ai** [comment]
I've addressed the code review feedback and fixed the failing test:

## Changes Made

1. **Moved helper functions to FileManager** - Per your review comments, I've moved  and  from the orchestrator to the FileManager class where they belong. This provides a cleaner separation of concerns.

2. **Updated orchestrator** - The orchestrator now uses the new FileManager methods instead of its own helper functions.

3. **Fixed failing integration test** - The test "should handle date-based incremental updates correctly" was failing because it was testing the old "yesterday" behavior. Since we now constrain to the max date in the block store, I updated the test to:
   - Add a historical date (2024-05-03) instead of a future date
   - Verify that the scanner processes up to this new max date
   - Check that the last scanned block is updated correctly

## Test Status
All 529 tests are now passing, including the previously failing integration test.

The changes maintain the same functionality while improving code organization as requested.

**Comment by yahgw-ai** [comment]
I've addressed the code review feedback and fixed the failing test:

## Changes Made

1. **Moved helper functions to FileManager** - Per your review comments, I've moved getMaxDateFromBlockStore and getMinDateFromBlockStore from the orchestrator to the FileManager class where they belong. This provides a cleaner separation of concerns.

2. **Updated orchestrator** - The orchestrator now uses the new FileManager methods instead of its own helper functions.

3. **Fixed failing integration test** - The test "should handle date-based incremental updates correctly" was failing because it was testing the old "yesterday" behavior. Since we now constrain to the max date in the block store, I updated the test to:
   - Add a historical date (2024-05-03) instead of a future date
   - Verify that the scanner processes up to this new max date
   - Check that the last scanned block is updated correctly

## Test Status
All 529 tests are now passing, including the previously failing integration test.

The changes maintain the same functionality while improving code organization as requested.

File: src/infrastructure/storage/file-manager.ts [hunk 4]
```diff
@@ -416,6 +416,50 @@ export class FileManager implements FileManagerInterface {
     }
   }
 
+  /**
+   * Gets the maximum date available in the block numbers store.
+   * @returns The maximum date as a Date object, or null if no dates exist
+   */
+  getMaxDateFromBlockStore(): Date | null {
+    const blockNumbersData = this.readBlockNumbers();
```
Comment (yahgwai) [inline src/infrastructure/storage/file-manager.ts:425]: there's a bunch of duplicate code in this and getMinDateFromBlockStore. please deduplicate. Also can we rename to getMax/MinDate

File: src/core/fee-calculation/recipient-recieved-scanner.ts [hunk 5]
```diff
@@ -178,6 +178,20 @@ export class RecipientRecievedScanner {
     }
   }
 
+  /**
+   * Gets the maximum date available in the block numbers store.
+   * @private
+   */
+  private getMaxDateFromBlockStore(
```
Comment (yahgwai) [inline src/core/fee-calculation/recipient-recieved-scanner.ts]: This should use the new filemanager method

**Comment by yahgw-ai** [comment]
I've addressed all the new review comments:

## Changes Made

1. **Deduplicated code in FileManager** - Extracted a private `getSortedDatesFromBlockStore()` helper method to eliminate the duplicate logic between the two date methods.

2. **Renamed methods** - Changed `getMaxDateFromBlockStore()` to `getMaxDate()` and `getMinDateFromBlockStore()` to `getMinDate()` as requested.

3. **Updated RecipientRecievedScanner** - Modified it to use the new FileManager method `getMaxDate()` instead of its own private method, removing the duplicate implementation.

4. **Updated all references** - Changed all calls to use the new method names throughout the codebase and tests.

## Summary
The code is now cleaner with no duplication, better method names, and proper separation of concerns. All 529 tests are passing.

**Review by yahgwai — APPROVED** [review]
